/* Auto-generated by genmsg_cpp for file /home/nazrul/fuerte_workspace/ptam/msg/points_visible.msg */
#ifndef PTAM_MESSAGE_POINTS_VISIBLE_H
#define PTAM_MESSAGE_POINTS_VISIBLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ptam
{
template <class ContainerAllocator>
struct points_visible_ {
  typedef points_visible_<ContainerAllocator> Type;

  points_visible_()
  : points_visible(0)
  {
  }

  points_visible_(const ContainerAllocator& _alloc)
  : points_visible(0)
  {
  }

  typedef int32_t _points_visible_type;
  int32_t points_visible;


  typedef boost::shared_ptr< ::ptam::points_visible_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptam::points_visible_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct points_visible
typedef  ::ptam::points_visible_<std::allocator<void> > points_visible;

typedef boost::shared_ptr< ::ptam::points_visible> points_visiblePtr;
typedef boost::shared_ptr< ::ptam::points_visible const> points_visibleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptam::points_visible_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptam::points_visible_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptam::points_visible_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptam::points_visible_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptam::points_visible_<ContainerAllocator> > {
  static const char* value() 
  {
    return "42add71f8f440e7303bc4883921935ff";
  }

  static const char* value(const  ::ptam::points_visible_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x42add71f8f440e73ULL;
  static const uint64_t static_value2 = 0x03bc4883921935ffULL;
};

template<class ContainerAllocator>
struct DataType< ::ptam::points_visible_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam/points_visible";
  }

  static const char* value(const  ::ptam::points_visible_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptam::points_visible_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 points_visible\n\
\n\
";
  }

  static const char* value(const  ::ptam::points_visible_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ptam::points_visible_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptam::points_visible_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.points_visible);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct points_visible_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptam::points_visible_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptam::points_visible_<ContainerAllocator> & v) 
  {
    s << indent << "points_visible: ";
    Printer<int32_t>::stream(s, indent + "  ", v.points_visible);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTAM_MESSAGE_POINTS_VISIBLE_H

