/* Auto-generated by genmsg_cpp for file /home/nazrul/fuerte_workspace/ptam/msg/pos_robot.msg */
#ifndef PTAM_MESSAGE_POS_ROBOT_H
#define PTAM_MESSAGE_POS_ROBOT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ptam
{
template <class ContainerAllocator>
struct pos_robot_ {
  typedef pos_robot_<ContainerAllocator> Type;

  pos_robot_()
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  pos_robot_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , theta(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _theta_type;
  double theta;


  typedef boost::shared_ptr< ::ptam::pos_robot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptam::pos_robot_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pos_robot
typedef  ::ptam::pos_robot_<std::allocator<void> > pos_robot;

typedef boost::shared_ptr< ::ptam::pos_robot> pos_robotPtr;
typedef boost::shared_ptr< ::ptam::pos_robot const> pos_robotConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptam::pos_robot_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptam::pos_robot_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptam::pos_robot_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptam::pos_robot_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptam::pos_robot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const  ::ptam::pos_robot_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ptam::pos_robot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptam/pos_robot";
  }

  static const char* value(const  ::ptam::pos_robot_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptam::pos_robot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 theta\n\
\n\
";
  }

  static const char* value(const  ::ptam::pos_robot_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ptam::pos_robot_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptam::pos_robot_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.theta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pos_robot_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptam::pos_robot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptam::pos_robot_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTAM_MESSAGE_POS_ROBOT_H

